name: Application Services Metering operator build

on:
  push:
    branches: [ main ]
    paths-ignore: [ '.gitignore', 'LICENSE', 'NOTICE', 'README*' ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths-ignore: [ '.gitignore', 'LICENSE', 'NOTICE', 'README*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1 
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn verify --file pom.xml --no-transfer-progress
